#include "\A3\ui_f\hpp\defineResincl.inc"
#include "\A3\ui_f_curator\ui\defineResinclDesign.inc"

//RscDisplayAttributeModuleCWSEnableDebugging
#define IDC_CWS_RscDisplayAttributeModuleCWSEnableDebugging_Value		43012

//RscDisplayAttributeModuleAppliesTo
#define IDC_CWS_RscDisplayAttributeModuleCWSAppliesTo_Value				43022

//RscDisplayAttributesModuleCWSConfig
#define IDD_CWS_RscDisplayAttributesModuleCWSConfig						44100
