#include "\A3\ui_f\hpp\defineResincl.inc"
#include "\A3\ui_f_curator\ui\defineResinclDesign.inc"

//RscDisplayAttributeModuleCWSEnableDebugging
#define IDC_CWS_RscDisplayAttributeModuleCWSEnableDebugging				43010
#define IDC_CWS_RscDisplayAttributeModuleCWSEnableDebugging_Title		43011
#define IDC_CWS_RscDisplayAttributeModuleCWSEnableDebugging_Value		43012

//RscDisplayAttributesModuleCWSConfig
#define IDD_CWS_RscDisplayAttributesModuleCWSConfig						44100
